// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2U8Kb9JjWFC821nBFlWwLs9YOlmHLlQU',
    appId: '1:969612623020:web:cf0c917fa201020802b309',
    messagingSenderId: '969612623020',
    projectId: 'psm-management',
    authDomain: 'psm-management.firebaseapp.com',
    storageBucket: 'psm-management.firebasestorage.app',
    measurementId: 'G-G6CBERQ5F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEHZ0Ekk99pFJqVFweNgxTSH_MwsTkbo8',
    appId: '1:969612623020:android:65cc3f8ddaa0de9e02b309',
    messagingSenderId: '969612623020',
    projectId: 'psm-management',
    storageBucket: 'psm-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-SCqX2xQT1OTW6OcR5OJK_0uQvlc_Ykk',
    appId: '1:969612623020:ios:c92d59383aef5f1d02b309',
    messagingSenderId: '969612623020',
    projectId: 'psm-management',
    storageBucket: 'psm-management.firebasestorage.app',
    iosBundleId: 'com.example.flutterSepg10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-SCqX2xQT1OTW6OcR5OJK_0uQvlc_Ykk',
    appId: '1:969612623020:ios:c92d59383aef5f1d02b309',
    messagingSenderId: '969612623020',
    projectId: 'psm-management',
    storageBucket: 'psm-management.firebasestorage.app',
    iosBundleId: 'com.example.flutterSepg10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2U8Kb9JjWFC821nBFlWwLs9YOlmHLlQU',
    appId: '1:969612623020:web:6888a04a37540b1002b309',
    messagingSenderId: '969612623020',
    projectId: 'psm-management',
    authDomain: 'psm-management.firebaseapp.com',
    storageBucket: 'psm-management.firebasestorage.app',
    measurementId: 'G-Y63Q42FHBD',
  );
}
